#!/bin/sh -e

# Login to vault if a token isn't set in the environment.
: "${VAULT_LOGIN_ARGS:=-method=aws}"
if [ -n "$VAULT_ADDR" ] && [ -n "$VAULT_SECRET_PATH" ] \
    && [ -z "$(vault print token)" ]
then
    vault login -no-print $VAULT_LOGIN_ARGS
fi

exec "$@"
